name 'customers'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures customers'
long_description 'Installs/Configures customers'
version '0.1.0'
